export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCESS = "GET_PRODUCT_SUCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";
export const CART_PRODUCTS = "CART_PRODUCTS";
export const DEC_PRODUCT = "DEC_PRODUCT";
export const SINGLE_PRODUCT_REMOVE = "SINGLE_PRODUCT_REMOVE";
export const CLEAR_CART = "CLEAR_CART";
export const SEARCH_FILTER = "SEARCH_FILTER";
